### PR TITLE
Shades_ColorGenerator by Ukesh-dev

### PR DESCRIPTION
**Pull request by Ukesh-dev**
# Shades-ColorGenerator

## A website for generating different colors and shades with the functionality of copying the generated color to the clipboard.

-Ukesh Shrestha

## Task Checklist
Put x in between the square brackets without any spaces to tick your Task.  Create a PR only after you complete all the tasks.
- [x ] You have created a new branch for contribution.
- [x ] Added README.md for your project in a specified folder.
- [x ] Add Demo in GIF or Screenshot form.
- [x ] You are Registered Officially for HacktoberFest 2021 as Partcipant.
- [x] Followed Contribution Guidelines.

## Issue 
Mention your issue no.

### CODE REVIEW

**Comment by soumik2012** [comment]
@Ukesh-dev I cannot see the issue ?? you made the PR without creating the issue.

**Comment by Ukesh-dev** [comment]
Why did you labeled it spam? The guideline does not suggest us to work only on issue.

**Comment by soumik2012** [comment]
Did you  read the [contributing.md](https://github.com/Tenet-Coding/Hacktoberfest-Projects/blob/master/CONTRIBUTING.md)
Here clearly mention please open up an issue first to discuss your proposed changes with a project maintainer! The issue will assgin to you then you can work on it.
image

**Comment by Ukesh-dev** [comment]
Would you mind removing the spam label ? It's clearly my fault for not reading the guidelines properly.

**Comment by soumik2012** [comment]
Okay @Ukesh-dev This is the last warning I will remove the tag next time please check the contributing guideline for any project don't make direct PR  to any project.Okay 😄

**Comment by Ukesh-dev** [comment]
Thank you so much. I will be careful from the next time. 
Part of the learning I guess.

**Pull request closed without merging**
