### PR TITLE
Commited Weather Forecast project

### LINKED ISSUE #17: Project :  Weather Forecast ⛈️
Make an application to predict the state of the atmosphere for a given location.
General Requirements :

- Create Toss, Either as a web page (More Preffered) or as Programming languages.
- An input for users to type city name
- Display current weather including weather condition, temperature, humidity, wind speed, and date and time
- Visualization to display the temperature change, humidity change, and weather conditions of each day
- Try to make GUI if you work with other programming languages.
- Show some of your creativity.

**Project Issues will be assigned on First Come First Serve basis after 1st October**

### PR DESCRIPTION
**Pull request by BajraYeJoon**
# Weather Forecast Web Application ☁☁

Get real live Weather Data. Search by City and it will show Temperature , State of your current city.

 
Closes #17 

- gif

## Task Checklist
Put x in between the square brackets without any spaces to tick your Task.  Create a PR only after you complete all the tasks.
- [x] You have created a new branch for contribution.
- [x] Added README.md for your project in a specified folder.
- [x] Add Demo in GIF or Screenshot form.
- [x] You are Registered Officially for HacktoberFest 2021 as Partcipant.
- [x] Followed Contribution Guidelines.

## Issue 
issue no. 41

### CODE REVIEW

**Comment by BajraYeJoon** [comment]
@soumik2012  Finally, got rid of it.  Now the branch is clean and Required project is only to be reviewed. Please check it.

Apologies for the incovenience.

**Review by soumik2012 — APPROVED** [review]
Everything nice and Prefect

**Comment by BajraYeJoon** [comment]
@Harshil-Jani  Please review this  Weather Forecast PR so that it will be shown accepted in Hacktobefest. 😃😃

**Comment by BajraYeJoon** [comment]
@soumik2012 @Harshil-Jani  I have a question, this contribution from mine in hacktoberfest profile is showing Matures in 14 days. what does it mean ? can you please clear my doubt😃

**Comment by soumik2012** [comment]
> @soumik2012 @Harshil-Jani I have a question, this contribution from mine in hacktoberfest profile is showing Matures in 14 days. what does it mean? can you please clear my doubt😃

@BajraYeJoon Actually it means that it takes 14 days to verify that PR is valid or not.

**Pull request merged**
