### PR TITLE
Weather forecast 

### LINKED ISSUE #17: Project :  Weather Forecast ⛈️
Make an application to predict the state of the atmosphere for a given location.
General Requirements :

- Create Toss, Either as a web page (More Preffered) or as Programming languages.
- An input for users to type city name
- Display current weather including weather condition, temperature, humidity, wind speed, and date and time
- Visualization to display the temperature change, humidity change, and weather conditions of each day
- Try to make GUI if you work with other programming languages.
- Show some of your creativity.

**Project Issues will be assigned on First Come First Serve basis after 1st October**

### PR DESCRIPTION
**Pull request by BajraYeJoon**
## Description

- Get real live Weather Data. Search by City and it will show Temperature , State of your current city.

Closes #17 

## GIF

- gif

## Task Checklist
- [x] You have created a new branch for contribution.
- [x] Added README.md for your project in a specified folder.
- [x] Add Demo in GIF or Screenshot form.
- [x] You are Registered Officially for HacktoberFest 2021 as Partcipant.
- [x] Followed Contribution Guidelines.

## Issue 
Issue No.17

### CODE REVIEW

**Review by soumik2012 — CHANGES_REQUESTED** [review]
- Why is the background color changer project is in the Weather forecast 🛑 ???

**Comment by BajraYeJoon** [comment]
I had pull request by creating new branch weather forecast and added all the files and I am also confused why this background color changer is showing up😥

**Comment by BajraYeJoon** [comment]
@soumik2012  I had delete the other project and only weather forecast files are remained . Please review it once again .

**Comment by soumik2012** [comment]
Hey @BajraYeJoon  please change your name I cannot fetch the branch 
image
wi

**Comment by soumik2012** [comment]
Have you made a new branch from the branch background_color project all the files are related to the background _color are also committed to the weather branch that's your problem. I will have to close this PR please make another PR.

**Comment by BajraYeJoon** [comment]
I will do it properly this time

**Pull request closed without merging**
