### PR TITLE
Memory Game

### LINKED ISSUE #28: Project : Memory game
Basically It is a card Game where you will be tested your memory.

### PR DESCRIPTION
**Pull request by 2devyank**
## Description

- Its a memory game which will test your memory

Closes #28 

## Add GIF/ScreenShot 
Untitled design (1)

## Task Checklist
Put x in between the square brackets without any spaces to tick your Task.  Create a PR only after you complete all the tasks.
- [x] You have created a new branch for contribution.
- [x] Added README.md for your project in a specified folder.
- [x] Add Demo in GIF or Screenshot form.
- [x] You are Registered Officially for HacktoberFest 2021 as Partcipant.
- [x] Followed Contribution Guidelines.

## Issue 
 your issue no. #28

### CODE REVIEW

**Comment by 2devyank** [comment]
@soumik2012 @Harshil-Jani  please check my pr and merge it

**Comment by Harshil-Jani** [comment]
@2devyank You are supposed to add it in new branch ! Not in the master (main) branch. Please do these changes !

**Comment by 2devyank** [comment]
@Harshil-Jani Oh I am really sorry . I will make the changes

**Comment by 2devyank** [comment]
@Harshil-Jani I have made the changes

**Comment by soumik2012** [comment]
@2devyank Please create another PR. Your branch is clean.

**Pull request closed without merging**
